### ISSUE TITLE
User can cycle through the carousel of recipes

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to change the recipe displayed in the carousel.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on a left or right arrow to change the recipe displayed in the carousel. The carousel will either go to the previous or next recipe out of a total of 10 recipes.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

#### Update Carousel
- [x] Create two react elements to represent opposite arrows using font awesome
- [x] Update styling for the two react elements

##### `right arrow`
  - [x] Increment the iterator
  - [x] Reset the interval
  - [x] Set the interval
  
  ##### `left arrow`
  - [x] Decrement the iterator
  - [x] Reset the interval
  - [x] Set the interval

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
