### ISSUE TITLE
User Can Delete Their Post

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/final-project#32]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users will be able to delete their comment.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks a trash can icon, they will be prompted to delete their comment. If the user didn't post the comment, user control features will not be available.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update database schema to have a deleted and deletedBy column
### ☁️ Server Tasks

- [x] Update `server/index.js` to receive a patch request from the user to delete their comment
- [x] Test with HTTPie

### ⚡ Client Tasks

- [x] Create a delete modal
- [x] Update styling
- [x] Update component functionality to respond to the users actions
- [x] Add onclick to handle clicks on buttons: Trash can icon, go back link, confirm delete button
- [x] Create a method for a fetch request to our server
- [x] If authorized, the patch request will be fulfilled

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
