### ISSUE TITLE
Refactor: Code Cleanup for v1

### ISSUE THREAD

**Issue by OSAdams** [OSAdams/final-project#38]
## ✅ Task List

- [x] Remove all unnecessary files and directories.
- [x] Use `lower-kebab-case` for all file and directory names.
- [x] Remove hard-coded tokens and credentials. **Renew tokens and credentials if accidentally hard-coded.**
- [x] Uninstall dependencies that were added but never actually used
- [x] Clean up all HTML files according to the guide.
- [x] Apply best practices described in the [effective-css](https://lfz-lms.herokuapp.com/code-guides/Learning-Fuze/curriculum/effective-css) guide.
- [x] Clean up all CSS files according to the guide.
- [x] Clean up all JavaScript / JSX files according to the guide.
- [x] Open a Pull Request.
- [x] Merge the Pull Request.
- [x] Send a link to the Pull Request to portfolio reviewer / instructor.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
